"""initial migration

Revision ID: 41664c41343e
Revises: 4428e0af1b81
Create Date: 2015-08-16 18:16:31.134458

"""

# revision identifiers, used by Alembic.
revision = '41664c41343e'
down_revision = '4428e0af1b81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
