"""initial migration

Revision ID: 4428e0af1b81
Revises: None
Create Date: 2015-08-16 18:14:19.255915

"""

# revision identifiers, used by Alembic.
revision = '4428e0af1b81'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
